# Generated by Django 5.2.15 on 2026-07-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(choices=[('preto', 'Preto'), ('branco', 'Branco'), ('cinza', 'Cinza'), ('azul', 'Azul Marinho'), ('verde', 'Verde'), ('vinho', 'Vinho'), ('bege', 'Bege'), ('areia', 'Areia'), ('rosa', 'Rosa'), ('cafe', 'Café'), ('capuccino', 'Capuccino')], max_length=20, verbose_name='Cor'),
        ),
    ]
