# Generated by Django 5.2.15 on 2026-06-26 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Aguardando Pagamento'), ('paid', 'Pago'), ('processing', 'Em Processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário')], default='pix', max_length=20, verbose_name='Forma de Pagamento')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Nome')),
                ('buyer_email', models.CharField(max_length=254, verbose_name='E-mail')),
                ('buyer_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('buyer_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('address_street', models.CharField(max_length=255, verbose_name='Rua')),
                ('address_number', models.CharField(max_length=20, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('address_neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(max_length=2, verbose_name='Estado')),
                ('address_zip', models.CharField(max_length=9, verbose_name='CEP')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('product_color', models.CharField(max_length=50, verbose_name='Cor')),
                ('product_size', models.CharField(max_length=10, verbose_name='Tamanho')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
