# Generated by Django 5.2.15 on 2026-07-12 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentagem (%)'), ('fixed', 'Valor Fixo (R$)')], default='percentage', max_length=20, verbose_name='Tipo de Desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Desconto')),
                ('min_purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mínimo de Compra')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido a partir de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de Usos')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Usos Efetuados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon'),
        ),
    ]
