# Generated by Django 5.2.15 on 2026-07-13 16:07

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='CPF'),
        ),
    ]
